/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangmx_jni_jnilibrary_JniInterface */

#ifndef _Included_com_wangmx_jni_jnilibrary_JniInterface
#define _Included_com_wangmx_jni_jnilibrary_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangmx_jni_jnilibrary_JniInterface
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangmx_jni_jnilibrary_JniInterface_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
